# Generated by Django 3.2 on 2021-05-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='collectorate_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('addr1', models.CharField(max_length=150)),
                ('addr2', models.CharField(max_length=150)),
                ('addr3', models.CharField(max_length=150)),
                ('pin', models.IntegerField()),
                ('district_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='disaster_followup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disaster_report_id', models.IntegerField()),
                ('remark', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='disaster_followup_allocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disaster_report_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='disaster_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disaster_name', models.CharField(max_length=50)),
                ('disaster_descp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='disaster_pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disaster_report_id', models.IntegerField()),
                ('pic_path', models.CharField(max_length=50)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='disaster_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('disaster_master_id', models.IntegerField()),
                ('addr', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('location_info', models.CharField(max_length=150)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='district_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
                ('state_master_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='district_news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district_id', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('news', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='general_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('g_type', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='official_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('name_details', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('district_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='state_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField()),
                ('msg', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=20)),
                ('addr1', models.CharField(max_length=150)),
                ('addr2', models.CharField(max_length=150)),
                ('addr3', models.CharField(max_length=150)),
                ('pin', models.IntegerField()),
                ('district_id', models.IntegerField()),
                ('id_name', models.CharField(max_length=50)),
                ('id_no', models.IntegerField()),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer_followup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField()),
                ('remark', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer_job_allocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('job_description', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('addr', models.CharField(max_length=150)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='age',
        ),
        migrations.AddField(
            model_name='user_details',
            name='addr1',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='addr2',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='addr3',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='district_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='dob',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='dt',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='id_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='id_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='tm',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
