# Generated by Django 3.2 on 2021-05-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210503_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
