# Generated by Django 3.2 on 2021-05-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
