# Generated by Django 3.2 on 2021-05-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_dob_user_details_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='addr1',
            new_name='addr',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='addr2',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='addr3',
        ),
    ]
