# Generated by Django 3.2 on 2021-05-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210504_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='district_id',
        ),
    ]
