# Generated by Django 3.2 on 2021-05-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_user_details_district_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='id_name',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='id_no',
        ),
    ]
