# Generated by Django 3.2 on 2021-05-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210504_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='passwd',
            field=models.CharField(default='SOME STRING', max_length=15),
        ),
    ]
