# Generated by Django 3.2 on 2021-05-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_details_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='u_type',
            field=models.CharField(max_length=25),
        ),
    ]
