# Generated by Django 3.2 on 2021-05-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_password_volunteer_details_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='passwd',
        ),
    ]
